
name: MarpCLI-GitHub-Actions
on:
  push:
    branches:
      - main
      - develop    
jobs:
  export:
    name: Exportar PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workflows:
              - 'Diapositivos/**'
      - name: Set input_dir
        run: |
          echo DATEVERSION=`date +%Y.%m.%d` >> $GITHUB_ENV
          while read line;
          do
            echo $line >> $GITHUB_ENV
          done<./Diapositivos/config
      - name: Create output DIR
        if: steps.filter.outputs.workflows == 'true'
        run: |
          mkdir ${{env.DST}}
          chmod 777 -R $_
      - name: Export PDF
        if: steps.filter.outputs.workflows == 'true'
        run: docker run --rm --init -v "$(pwd):/home/marp/app/"
          -e MARPID="$(id -u):$(id -g)" marpteam/marp-cli:v1.5.0
          --${{env.FORMAT}}
          -I ${{env.DIR}}
          -o ${{env.DST}}
          --allow-local-files
      - name: Create Releases
        if: steps.filter.outputs.workflows == 'true'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{env.DST}}/TPSIVFX2122_A*
          token: ${{ secrets.CR_PAT }}
          tag: 'v${{env.DATEVERSION}}'
          name: '[${{env.DATEVERSION}}]'